### ISSUE TITLE
No longer builds on OS X 10.12.2

### ISSUE THREAD

**Issue by iosdev-republicofapps** [fuyu/ChromeMenu#1]
/Users/joel/Downloads/ChromeMenu-master/ChromeMenu/src/CMWindowController.m:1489:18: error: '_owner' is unavailable
        CMMenu *menu = [_owner menuAtPoint:mouseLocation];
                        ^
/Users/joel/Downloads/ChromeMenu-master/ChromeMenu/src/CMWindowController.m:48:17: note: declaration uses __weak, but ARC is disabled
        __weak CMMenu *_owner;
                       ^
/Users/joel/Downloads/ChromeMenu-master/ChromeMenu/src/CMWindowController.m:48:17: error: cannot create __weak reference in file using manual reference counting
        __weak CMMenu *_owner;

**Comment by SSebo** [comment]
change 'References in Manual Retain Release' to YES, in xcode build settings

**Comment by SSebo** [comment]
![image](https://user-images.githubusercontent.com/5784607/27115107-fc52e1fe-50fa-11e7-9b86-170a05ba882a.png)
